trainer:
  name: "CIFAR10"
  train_batch_size: 128
  val_batch_size: 64
  tensorboard_log_dir: "/content/logs"
  lr: 2e-4
  device: "auto"
  load_ckpt: False
  checkpoint_dir: "./models/"
  min_lr: 1e-7
  disc_lr: 2e-4
  warmup: False
  warmup_steps: 0.1

  # Discriminator config
  disc_start: 3000
  disc_weight: 0.5
  adversarial_weight: 0.1
  use_adaptive_weight: False
  grad_acc_steps: 1
  
  # Optimizer config
  weight_decay: 0.01
  gradient_clip_val: 1.0
  d_weight_max: 50.0
  
encoder:
  resolution: 32
  in_channels: 3
  out_channels: 32
  num_resblocks: 3
  ch_factor: 64
  ch_mult: [1, 2, 4]


quantizer:
  type: "kl"
  params:
    in_channels: 32
    embed_dim: 32
    beta: 1e-4
    reduce_mean: True

decoder:
  resolution: 32
  in_channels: 32
  out_channels: 3
  num_resblocks: 3
  attn_resolutions: []
  ch: 64
  ch_mult: [1, 4, 4]


perceptual_loss:
  layers: [1,6,11,20,29]
  normalized: True
  scale: 0.0001
  device: "cuda:0"

disc_config:
  input_nc: 3
  ndf: 64
  n_layers: 3

