trainer:
  name: "CIFAR10"
  train_batch_size: 128
  val_batch_size: 64
  max_epochs: 100
  tensorboard_log_dir: "./logs"
  checkpoint_dir: "./models/"
  lr: 2e-4
  min_lr: 1e-7
  device: "auto"
  warmup: False
  warmup_steps: 0.1
  load_ckpt: False
  # Optimizer config
  weight_decay: 0.01
  gradient_clip_val: 1.0
encoder:
  resolution: 32
  in_channels: 3
  out_channels: 3
  num_resblocks: 3
  ch_factor: 64
  ch_mult: [1, 2, 4]


quantizer:
  type: "ema"
  params:
    codebook_size: 2048
    embed_dim: 3
    commit_cost: 0.5

decoder:
  resolution: 32
  in_channels: 3
  out_channels: 3
  num_resblocks: 3
  attn_resolutions: []
  ch: 64
  ch_mult: [1, 4, 4]


perceptual_loss:
  layers: [1,6,11,20,29]
  normalized: True
  scale: 0.01

