trainer:
  name: "CIFA10"
  train_batch_size: 128
  val_batch_size: 64
  tensorboard_log_dir: "/mnt/sda/ab/projects/FY24/cmc/logs"
  lr: 1e-3
  device: "cuda:0"
  
encoder:
  resolution: 32
  in_channels: 3
  out_channels: 3
  num_resblocks: 3
  ch_factor: 64
  ch_mult: [1, 4, 8]


quantizer:
  use_ema: True
  codebook_size: 2048
  embed_dim: 4
  commit_cost: 0.25

decoder:
  resolution: 32
  in_channels: 3
  out_channels: 3
  num_resblocks: 3
  attn_resolutions: []
  ch: 64
  ch_mult: [1, 4, 8]


perceptual_loss:
  layers: []
  normalized: True
  scale: 0.01
  device: "cuda:0"

