trainer:
  name: "Coco17-16x16x8-lr-sched"
  train_batch_size: 32
  val_batch_size: 32
  max_epochs: 25
  tensorboard_log_dir: "./logs"
  checkpoint_dir: "./models/"
  lr: 0.0001
  min_lr: 1e-7
  device: "cuda"
  warmup: True
  warmup_steps: 0.1
  load_ckpt: False
  # Optimizer config
  weight_decay: 0.01
  gradient_clip_val: 1.0

data:
  train_root: "./data/coco17/train2017"
  train_ann: "./data/coco17/annotations/captions_train2017.json"
  val_root: "./data/coco17/val2017"
  val_ann: "./data/coco17/annotations/captions_val2017.json"
  
encoder:
  resolution: 128
  in_channels: 3
  out_channels: 8
  num_resblocks: 3
  ch_factor: 64
  ch_mult: [1, 2, 2, 4]
  attn_resolutions: []

quantizer:
  type: "ema"
  params:
    codebook_size: 4096
    embed_dim: 8
    commit_cost: 0.25

decoder:
  resolution: 128
  in_channels: 8
  out_channels: 3
  num_resblocks: 3
  attn_resolutions: []
  ch: 64
  ch_mult: [1, 2, 2, 4]


perceptual_loss:
  layers: [1, 6, 11, 20, 29]
  normalized: True
  scale: 0.01

