encoder:
  resolution: 32
  in_channels: 3
  out_channels: 256
  num_resblocks: 3
  ch_factor: 64
  ch_mult: [1, 4, 8]
  mid_block: False

quantizer:
  use_ema: True
  codebook_size: 128
  embed_dim: 256
  commit_cost: 0.25

decoder:
  
